'use client'
import { useState } from 'react'
import Link from 'next/link'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import {
  ChevronRight, Users, DollarSign, TrendingUp, CheckCircle2,
  ArrowRight, Zap, Globe2, Award, Copy, Check
} from 'lucide-react'

const steps = [
  { n: '01', icon: Users,      title: 'Join the Program',    desc: 'Apply below with your name and email. Approvals are processed within 24 hours and you\'ll receive your unique referral link.' },
  { n: '02', icon: Globe2,     title: 'Share Your Link',     desc: 'Share your referral link with your network — social media, email, blog, or through your own sales team.' },
  { n: '03', icon: DollarSign, title: 'Earn 15% for Life',   desc: 'Every time someone signs up through your link, you earn 15% of every transaction they ever make — for the lifetime of their account.' },
  { n: '04', icon: TrendingUp, title: 'Build Your Sales Team', desc: 'Invite others to become affiliates under you. You earn an extra 5% on all transactions made by your entire sales team.' },
]

const perks = [
  { icon: Award,      title: 'Lifetime 15%',       desc: 'Earn 15% on every transaction your referrals make — forever, not just the first purchase.' },
  { icon: Users,      title: '5% Sales Team Bonus', desc: 'Build your own sales team and earn 5% of all their referral transactions on top of your own.' },
  { icon: Zap,        title: 'Instant Payouts',     desc: 'Request payouts anytime. We pay via bank transfer, PayPal, or crypto. No minimum holding period.' },
  { icon: TrendingUp, title: 'Real-Time Dashboard', desc: 'Track your referrals, sales team activity, and earnings in real-time through your affiliate portal.' },
  { icon: Globe2,     title: 'High-Value Products', desc: 'Our company formation, trademark, and DMCA services average $500+ per transaction — your 15% adds up fast.' },
  { icon: DollarSign, title: 'No Cap, Ever',        desc: 'There is no ceiling on your earnings. The more you refer and the bigger your sales team grows, the more you make.' },
]

const faqs = [
  { q: 'How are commissions tracked?', a: 'Every referral is tracked via your unique link with a 90-day cookie. If someone clicks your link and purchases within 90 days, you get the commission even if they don\'t sign up immediately.' },
  { q: 'When do I get paid?', a: 'Payouts are processed every 2 weeks. You can request a payout at any time from your portal — minimum payout is $50.' },
  { q: 'How does the Sales Team commission work?', a: 'When you invite someone to become an affiliate under you, they become part of your sales team. You earn 5% of all transactions generated by your entire sales team, in addition to your own 15% referrals. There is one level of sales team.' },
  { q: 'What payment methods do you support?', a: 'We pay via wire transfer, PayPal, and cryptocurrency (Bitcoin, USDC, ETH). Payment details can be managed in your affiliate portal.' },
  { q: 'Is there a minimum referral requirement?', a: 'No. You keep your affiliate status even with zero referrals. There are no monthly minimums or performance requirements.' },
  { q: 'Can I be both an Atlas client and an affiliate?', a: 'Yes — many of our best affiliates are also clients. There is no conflict of interest and your own purchases do not generate commission.' },
]

export default function AffiliatesPage() {
  const [refCount, setRefCount] = useState(10)
  const [teamSize, setTeamSize] = useState(3)
  const avgTxn = 550
  const myEarnings = Math.round(refCount * avgTxn * 0.15)
  const teamEarnings = Math.round(teamSize * 5 * avgTxn * 0.05)
  const totalMonthly = myEarnings + teamEarnings

  const [form, setForm] = useState({ name: '', email: '', website: '', how: '' })
  const [submitted, setSubmitted] = useState(false)
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!form.name || !form.email) return
    setLoading(true)
    setTimeout(() => { setLoading(false); setSubmitted(true) }, 1400)
  }

  const copyRefLink = () => {
    navigator.clipboard.writeText('https://atlas.co/ref/YOURCODE')
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="min-h-screen">
      <Navbar />

      {/* ─── Hero ─── */}
      <section className="relative pt-32 pb-20 px-6 overflow-hidden dot-grid">
        <div className="glow-orb w-[700px] h-[700px] opacity-15"
          style={{ background: 'radial-gradient(circle, rgba(220,38,38,0.4) 0%, transparent 70%)', top: '-15%', left: '50%', transform: 'translateX(-50%)' }} />
        <div className="max-w-5xl mx-auto text-center relative z-10">
          <div className="section-badge"><DollarSign size={14} /> Affiliate Program</div>
          <h1 className="text-5xl md:text-7xl font-bold mb-6 leading-tight">
            Earn <span className="gold-text">15% for Life</span><br />on Every Referral
          </h1>
          <p className="text-xl text-white/60 max-w-3xl mx-auto mb-10 leading-relaxed">
            Refer clients to Atlas and earn 15% commission on every transaction they make — forever.
            Build your own sales team and earn an extra 5% on all their referrals too.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <a href="#join" className="gold-btn inline-flex items-center gap-2 text-base px-8 py-4">
              Join the Program <ChevronRight size={18} />
            </a>
            <Link href="/affiliates/portal" className="px-8 py-4 rounded-xl border border-white/15 font-semibold text-white/70 hover:text-white hover:border-white/30 transition-all duration-200 inline-flex items-center gap-2">
              Affiliate Portal <ArrowRight size={18} />
            </Link>
            <Link href="/affiliates/resources" className="px-8 py-4 rounded-xl border border-white/10 font-semibold text-white/45 hover:text-white/70 hover:border-white/20 transition-all duration-200 inline-flex items-center gap-2 text-base">
              Marketing Kit <ArrowRight size={18} />
            </Link>
          </div>
        </div>
      </section>

      {/* ─── Commission Snapshot ─── */}
      <section className="px-6 pb-20">
        <div className="max-w-5xl mx-auto grid md:grid-cols-3 gap-6">
          {[
            { label: 'Your Commission', value: '15%', sub: 'Of every transaction, forever', color: '#DC2626' },
            { label: 'Sales Team Bonus', value: '+5%', sub: 'Of all your sales team transactions', color: '#EF4444' },
            { label: 'Avg. Transaction', value: '$550+', sub: 'Average client transaction value', color: '#fff' },
          ].map(s => (
            <div key={s.label} className="glass-card p-8 text-center" style={{ boxShadow: s.color === '#DC2626' ? '0 0 30px rgba(220,38,38,0.08)' : '' }}>
              <div className="text-5xl font-bold mb-2" style={{ color: s.color }}>{s.value}</div>
              <div className="font-semibold text-white mb-1">{s.label}</div>
              <div className="text-sm text-white/45">{s.sub}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ─── Earnings Calculator ─── */}
      <section className="py-20 px-6" style={{ background: 'var(--bg-alt)' }}>
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <div className="section-badge"><TrendingUp size={14} /> Earnings Calculator</div>
            <h2 className="section-headline">How Much Could You Make?</h2>
            <p className="section-sub">Adjust the sliders to estimate your monthly earnings.</p>
          </div>
          <div className="glass-card p-8 md:p-12">
            <div className="grid md:grid-cols-2 gap-12">
              <div className="space-y-8">
                {/* My referrals slider */}
                <div>
                  <div className="flex justify-between mb-3">
                    <label className="text-sm font-medium text-white/70">My Monthly Referrals</label>
                    <span className="text-sm font-bold text-white">{refCount} clients</span>
                  </div>
                  <input type="range" min={1} max={50} value={refCount}
                    onChange={e => setRefCount(+e.target.value)}
                    className="w-full accent-red-500 h-2 rounded-lg appearance-none cursor-pointer"
                    style={{ background: `linear-gradient(to right, #DC2626 0%, #DC2626 ${(refCount/50)*100}%, rgba(255,255,255,0.1) ${(refCount/50)*100}%, rgba(255,255,255,0.1) 100%)` }}
                  />
                  <div className="flex justify-between text-xs text-white/30 mt-1"><span>1</span><span>50</span></div>
                </div>
                {/* Sales team slider */}
                <div>
                  <div className="flex justify-between mb-3">
                    <label className="text-sm font-medium text-white/70">My Sales Team Size</label>
                    <span className="text-sm font-bold text-white">{teamSize} affiliates</span>
                  </div>
                  <input type="range" min={0} max={20} value={teamSize}
                    onChange={e => setTeamSize(+e.target.value)}
                    className="w-full accent-red-500 h-2 rounded-lg appearance-none cursor-pointer"
                    style={{ background: `linear-gradient(to right, #DC2626 0%, #DC2626 ${(teamSize/20)*100}%, rgba(255,255,255,0.1) ${(teamSize/20)*100}%, rgba(255,255,255,0.1) 100%)` }}
                  />
                  <div className="flex justify-between text-xs text-white/30 mt-1"><span>0</span><span>20</span></div>
                </div>
                <div className="text-xs text-white/30 leading-relaxed pt-2 border-t border-white/8">
                  * Based on {teamSize} sales team members each referring 5 clients/month at avg. ${avgTxn} transaction value.
                </div>
              </div>

              {/* Results */}
              <div className="flex flex-col justify-center space-y-5">
                <div className="glass-card p-5">
                  <div className="text-xs text-white/40 mb-1">My Referral Earnings (15%)</div>
                  <div className="text-3xl font-bold text-white">${myEarnings.toLocaleString()}<span className="text-base text-white/40 font-normal">/mo</span></div>
                  <div className="text-xs text-white/35 mt-1">{refCount} referrals × ${avgTxn} × 15%</div>
                </div>
                <div className="glass-card p-5">
                  <div className="text-xs text-white/40 mb-1">Sales Team Bonus (5%)</div>
                  <div className="text-3xl font-bold text-white">${teamEarnings.toLocaleString()}<span className="text-base text-white/40 font-normal">/mo</span></div>
                  <div className="text-xs text-white/35 mt-1">{teamSize} affiliates × 5 referrals × ${avgTxn} × 5%</div>
                </div>
                <div className="glass-card p-5 border-red-600/30" style={{ boxShadow: '0 0 20px rgba(220,38,38,0.08)' }}>
                  <div className="text-xs text-white/40 mb-1">Total Monthly Earnings</div>
                  <div className="text-4xl font-bold gold-text">${totalMonthly.toLocaleString()}</div>
                  <div className="text-xs text-white/35 mt-1">${(totalMonthly * 12).toLocaleString()} annually</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ─── How It Works ─── */}
      <section className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <div className="section-badge"><Zap size={14} /> How It Works</div>
            <h2 className="section-headline">Simple. Transparent. Lucrative.</h2>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {steps.map(s => (
              <div key={s.n} className="glass-card p-6 hover:border-red-600/30 transition-all duration-300 group">
                <div className="text-4xl font-black text-white/5 mb-3 leading-none">{s.n}</div>
                <div className="w-11 h-11 rounded-xl flex items-center justify-center mb-4 -mt-6"
                  style={{ background: 'rgba(220,38,38,0.12)', border: '1px solid rgba(220,38,38,0.2)' }}>
                  <s.icon size={20} className="text-red-400" />
                </div>
                <h3 className="font-semibold text-white mb-2">{s.title}</h3>
                <p className="text-sm text-white/50 leading-relaxed">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── Perks ─── */}
      <section className="py-20 px-6" style={{ background: 'var(--bg-alt)' }}>
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="section-headline">Everything Included</h2>
            <p className="section-sub">No catches. No hidden terms. Just straightforward commissions.</p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {perks.map(p => (
              <div key={p.title} className="glass-card p-6 hover:border-red-600/30 transition-all duration-300 group">
                <div className="w-11 h-11 rounded-xl flex items-center justify-center mb-4"
                  style={{ background: 'rgba(220,38,38,0.12)', border: '1px solid rgba(220,38,38,0.2)' }}>
                  <p.icon size={20} className="text-red-400" />
                </div>
                <h3 className="font-semibold text-white mb-2">{p.title}</h3>
                <p className="text-sm text-white/50 leading-relaxed">{p.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── Preview of ref link ─── */}
      <section className="py-14 px-6">
        <div className="max-w-2xl mx-auto text-center">
          <p className="text-white/40 text-sm mb-3">Your referral link will look like this after joining:</p>
          <div className="glass-card p-4 flex items-center justify-between gap-4">
            <code className="text-sm text-red-400 flex-1 text-left truncate">https://atlas.co/ref/YOURCODE</code>
            <button onClick={copyRefLink}
              className="flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium border transition-all duration-200"
              style={{ border: '1px solid rgba(220,38,38,0.3)', background: 'rgba(220,38,38,0.08)', color: copied ? '#4ade80' : '#DC2626' }}>
              {copied ? <><Check size={13}/> Copied!</> : <><Copy size={13}/> Copy</>}
            </button>
          </div>
        </div>
      </section>

      {/* ─── FAQ ─── */}
      <section className="py-20 px-6" style={{ background: 'var(--bg-alt)' }}>
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="section-headline">Frequently Asked Questions</h2>
          </div>
          <div className="space-y-4">
            {faqs.map(f => (
              <div key={f.q} className="glass-card p-6">
                <h3 className="font-semibold text-white mb-2">{f.q}</h3>
                <p className="text-sm text-white/55 leading-relaxed">{f.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── Join Form ─── */}
      <section id="join" className="py-24 px-6">
        <div className="max-w-2xl mx-auto">
          {submitted ? (
            <div className="glass-card p-14 text-center">
              <div className="w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6"
                style={{ background: 'rgba(220,38,38,0.15)', border: '1px solid rgba(220,38,38,0.3)' }}>
                <CheckCircle2 size={36} className="text-red-400" />
              </div>
              <h2 className="text-3xl font-bold mb-3">Application Submitted!</h2>
              <p className="text-white/55 mb-8 max-w-sm mx-auto">We&apos;ll review your application and send your affiliate link and portal access within 24 hours.</p>
              <Link href="/affiliates/portal" className="gold-btn inline-flex items-center gap-2">
                View Your Portal <ChevronRight size={18} />
              </Link>
            </div>
          ) : (
            <div className="glass-card p-8 md:p-12">
              <div className="text-center mb-8">
                <div className="section-badge mx-auto mb-4"><Award size={14} /> Join Free</div>
                <h2 className="text-3xl font-bold">Apply to Become an Affiliate</h2>
                <p className="text-white/50 mt-2">Free to join. No monthly fees. Start earning in 24 hours.</p>
              </div>
              <form onSubmit={handleSubmit} className="space-y-5">
                <div className="grid sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-white/70 mb-2">Full Name</label>
                    <input id="aff-name" type="text" className="atlas-input" placeholder="John Smith"
                      value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} required />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-white/70 mb-2">Email Address</label>
                    <input id="aff-email" type="email" className="atlas-input" placeholder="john@company.com"
                      value={form.email} onChange={e => setForm(f => ({ ...f, email: e.target.value }))} required />
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-white/70 mb-2">Website / Social Profile (Optional)</label>
                  <input id="aff-website" type="url" className="atlas-input" placeholder="https://yourwebsite.com"
                    value={form.website} onChange={e => setForm(f => ({ ...f, website: e.target.value }))} />
                </div>
                <div>
                  <label className="block text-sm font-medium text-white/70 mb-2">How will you promote Atlas?</label>
                  <textarea id="aff-how" className="atlas-input min-h-[100px] resize-none"
                    placeholder="e.g. Blog, newsletter, LinkedIn, YouTube, referrals from my network..."
                    value={form.how} onChange={e => setForm(f => ({ ...f, how: e.target.value }))} />
                </div>
                <button id="aff-submit" type="submit" disabled={loading}
                  className="gold-btn w-full flex items-center justify-center gap-2 disabled:opacity-60">
                  {loading
                    ? <span className="flex items-center gap-2"><span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Processing…</span>
                    : <>Submit Application <ChevronRight size={18} /></>}
                </button>
                <p className="text-center text-xs text-white/30">
                  By applying you agree to our <Link href="/legal/terms" className="text-red-400 hover:underline">Terms of Service</Link> and{' '}
                  <Link href="/legal/privacy" className="text-red-400 hover:underline">Privacy Policy</Link>.
                </p>
              </form>
            </div>
          )}
        </div>
      </section>

      <Footer />
    </div>
  )
}
